In [1]:
import numpy as np
import pandas as pd
array_2d = np.random.randint(50,100,size=(50,5))
df1 = pd.DataFrame(array_2d,
             columns=['國文','英文','數學','自然','社會'],   #欄位
             index = [f'{num}號' for num in range(1,51)],   #索引
             )

df1

     國文  英文  數學  自然  社會
1號   50  82  80  72  52
2號   95  77  99  57  75
3號   91  90  53  62  78
4號   79  79  57  88  97
5號   93  77  55  87  91
6號   55  73  50  81  62
7號   84  71  75  89  56
8號   54  89  95  78  62
9號   81  83  85  64  50
10號  56  90  75  56  95
11號  86  91  85  59  51
12號  97  86  84  69  90
13號  90  52  50  99  85
14號  74  93  64  85  78
15號  88  79  98  83  56
16號  79  61  99  65  97
17號  83  86  59  55  51
18號  61  66  73  96  87
19號  87  57  64  92  94
20號  90  56  74  67  86
21號  85  50  51  67  66
22號  94  51  70  72  87
23號  57  56  63  60  71
24號  63  78  68  56  66
25號  76  61  58  54  84
26號  71  83  99  86  84
27號  52  60  63  52  57
28號  92  67  63  87  65
29號  94  92  95  67  71
30號  54  52  82  90  65
31號  83  54  93  58  68
32號  59  67  96  90  73
33號  68  86  74  66  77
34號  70  66  64  77  97
35號  92  87  51  87  67
36號  50  65  82  58  54
37號  98  67  72  68  99
38號  96  56  77  64  54
39號  62  64  69  81  91
40號  88  92  96  91  96
41號  97  80  89  55  86
42號  74  89  83  95  79
43號  99  79  73  78  86
44號  99  60  93  62  67
45號  55  57  64  53  92
46號  84  69  74  81  96
47號  57  63  99  95  97
48號  82  96  83  79  79
49號  60  67  99  56  56
50號  91  61  98  73  51

In [2]:
# ndarray 最好用的即為 陣列運算
total_se = df1['國文'] + df1['英文'] + df1['數學'] + df1['自然'] + df1['社會']
total_se

1號     336
2號     403
3號     374
4號     400
5號     403
6號     321
7號     375
8號     378
9號     363
10號    372
11號    372
12號    426
13號    376
14號    394
15號    404
16號    401
17號    334
18號    383
19號    394
20號    373
21號    319
22號    374
23號    307
24號    331
25號    333
26號    423
27號    284
28號    374
29號    419
30號    343
31號    356
32號    385
33號    371
34號    374
35號    384
36號    309
37號    404
38號    347
39號    367
40號    463
41號    407
42號    420
43號    415
44號    381
45號    321
46號    404
47號    411
48號    419
49號    338
50號    374
dtype: int32

In [3]:
average_se = total_se / 5
average_se

1號     67.2
2號     80.6
3號     74.8
4號     80.0
5號     80.6
6號     64.2
7號     75.0
8號     75.6
9號     72.6
10號    74.4
11號    74.4
12號    85.2
13號    75.2
14號    78.8
15號    80.8
16號    80.2
17號    66.8
18號    76.6
19號    78.8
20號    74.6
21號    63.8
22號    74.8
23號    61.4
24號    66.2
25號    66.6
26號    84.6
27號    56.8
28號    74.8
29號    83.8
30號    68.6
31號    71.2
32號    77.0
33號    74.2
34號    74.8
35號    76.8
36號    61.8
37號    80.8
38號    69.4
39號    73.4
40號    92.6
41號    81.4
42號    84.0
43號    83.0
44號    76.2
45號    64.2
46號    80.8
47號    82.2
48號    83.8
49號    67.6
50號    74.8
dtype: float64

In [4]:
df1['總分'] = total_se
df1['平均'] = average_se
df1

     國文  英文  數學  自然  社會   總分    平均
1號   50  82  80  72  52  336  67.2
2號   95  77  99  57  75  403  80.6
3號   91  90  53  62  78  374  74.8
4號   79  79  57  88  97  400  80.0
5號   93  77  55  87  91  403  80.6
6號   55  73  50  81  62  321  64.2
7號   84  71  75  89  56  375  75.0
8號   54  89  95  78  62  378  75.6
9號   81  83  85  64  50  363  72.6
10號  56  90  75  56  95  372  74.4
11號  86  91  85  59  51  372  74.4
12號  97  86  84  69  90  426  85.2
13號  90  52  50  99  85  376  75.2
14號  74  93  64  85  78  394  78.8
15號  88  79  98  83  56  404  80.8
16號  79  61  99  65  97  401  80.2
17號  83  86  59  55  51  334  66.8
18號  61  66  73  96  87  383  76.6
19號  87  57  64  92  94  394  78.8
20號  90  56  74  67  86  373  74.6
21號  85  50  51  67  66  319  63.8
22號  94  51  70  72  87  374  74.8
23號  57  56  63  60  71  307  61.4
24號  63  78  68  56  66  331  66.2
25號  76  61  58  54  84  333  66.6
26號  71  83  99  86  84  423  84.6
27號  52  60  63  52  57  284  56.8
28號  92  67  63  87  65  374  74.8
29號  94  92  95  67  71  419  83.8
30號  54  52  82  90  65  343  68.6
31號  83  54  93  58  68  356  71.2
32號  59  67  96  90  73  385  77.0
33號  68  86  74  66  77  371  74.2
34號  70  66  64  77  97  374  74.8
35號  92  87  51  87  67  384  76.8
36號  50  65  82  58  54  309  61.8
37號  98  67  72  68  99  404  80.8
38號  96  56  77  64  54  347  69.4
39號  62  64  69  81  91  367  73.4
40號  88  92  96  91  96  463  92.6
41號  97  80  89  55  86  407  81.4
42號  74  89  83  95  79  420  84.0
43號  99  79  73  78  86  415  83.0
44號  99  60  93  62  67  381  76.2
45號  55  57  64  53  92  321  64.2
46號  84  69  74  81  96  404  80.8
47號  57  63  99  95  97  411  82.2
48號  82  96  83  79  79  419  83.8
49號  60  67  99  56  56  338  67.6
50號  91  61  98  73  51  374  74.8

In [5]:
# Series 使用比較運算子
df1['總分'] >= 400

1號     False
2號      True
3號     False
4號      True
5號      True
6號     False
7號     False
8號     False
9號     False
10號    False
11號    False
12號     True
13號    False
14號    False
15號     True
16號     True
17號    False
18號    False
19號    False
20號    False
21號    False
22號    False
23號    False
24號    False
25號    False
26號     True
27號    False
28號    False
29號     True
30號    False
31號    False
32號    False
33號    False
34號    False
35號    False
36號    False
37號     True
38號    False
39號    False
40號     True
41號     True
42號     True
43號     True
44號    False
45號    False
46號     True
47號     True
48號     True
49號    False
50號    False
Name: 總分, dtype: bool

In [6]:
# 使用 dataFrame/subscript 搜尋資料
# dataFrame[bool Series]

df1[df1['總分'] >= 400]

     國文  英文  數學  自然  社會   總分    平均
2號   95  77  99  57  75  403  80.6
4號   79  79  57  88  97  400  80.0
5號   93  77  55  87  91  403  80.6
12號  97  86  84  69  90  426  85.2
15號  88  79  98  83  56  404  80.8
16號  79  61  99  65  97  401  80.2
26號  71  83  99  86  84  423  84.6
29號  94  92  95  67  71  419  83.8
37號  98  67  72  68  99  404  80.8
40號  88  92  96  91  96  463  92.6
41號  97  80  89  55  86  407  81.4
42號  74  89  83  95  79  420  84.0
43號  99  79  73  78  86  415  83.0
46號  84  69  74  81  96  404  80.8
47號  57  63  99  95  97  411  82.2
48號  82  96  83  79  79  419  83.8

In [7]:
# 查詢平均95分以上
df1[df1['平均'] >= 85]

     國文  英文  數學  自然  社會   總分    平均
12號  97  86  84  69  90  426  85.2
40號  88  92  96  91  96  463  92.6

In [8]:
# 查詢平均85分以上 同時數學90分以上
# and = &
# or = |
df1[(df1['平均'] >= 85) & (df1['英文'] >=90)]

     國文  英文  數學  自然  社會   總分    平均
40號  88  92  96  91  96  463  92.6