In [1]:
import numpy as np
import pandas as pd

score = pd.DataFrame(np.random.randint(50,101,size=(50,5)),
             columns=['國文','英文','數學','自然','社會'],
             index=range(1,51))

score

     國文  英文   數學   自然   社會
1    92  82   72   91   58
2    73  86   85   98   86
3    64  69   50   81   88
4   100  59   58   52   93
5    53  84   69   94   74
6    64  63   88   56   57
7    90  87   78   65   73
8    97  66   94   69   61
9    80  60   54  100   93
10   62  93   64   66   92
11   57  56   99   93   75
12   93  93   63   96   92
13   78  51   62   68   70
14   90  52   55   91   57
15   70  90   51   71   50
16   57  88   57   66   90
17   58  93   62   58   97
18   74  82   64  100   58
19   97  92   60   79   73
20   66  85   69   98   75
21   50  73   81   98   76
22   76  51   67   59   85
23   79  83   71   86   89
24   55  91   53   66   88
25   67  59   69   83   89
26   75  85  100   96   82
27   54  65   57   78   88
28   51  72   91   77   75
29   94  85   86   81   80
30   71  59   90   73   76
31   80  91   95   66   78
32   62  89   57   84   72
33   93  80   52   90   79
34   52  72   52   59   98
35   53  80   53   71   64
36   99  71   90   67   69
37   66  58   59   95   91
38   70  85   59   94   70
39   65  90   76   82   58
40   60  94   77   91   89
41   63  74   83   66   72
42   85  50   85   65  100
43   88  68   56   72   69
44   84  53   97   71   55
45   58  61   59   92   74
46   96  99   84   53   68
47   53  90   75   56   52
48   57  96   70   88   50
49   70  68   67   87   89
50   90  92   65   84   71

DataFrame.apply(func, axis=0, raw=False, result_type=None, args=(), by_row='compat', engine='python', engine_kwargs=None, **kwargs)[source]
- Apply a function along an axis of the DataFrame.
- 调用一个函数（Python method），让此函数对数据对象进行批量处理。

Lambda函式，也就是匿名函式，不需要定義名稱，只有一行運算式，語法非常簡潔

In [2]:
score.apply(lambda item:print(item))

# 將DataFrame中 所有Series 傳入 apply 並合併成一個 Series

1      92
2      73
3      64
4     100
5      53
6      64
7      90
8      97
9      80
10     62
11     57
12     93
13     78
14     90
15     70
16     57
17     58
18     74
19     97
20     66
21     50
22     76
23     79
24     55
25     67
26     75
27     54
28     51
29     94
30     71
31     80
32     62
33     93
34     52
35     53
36     99
37     66
38     70
39     65
40     60
41     63
42     85
43     88
44     84
45     58
46     96
47     53
48     57
49     70
50     90
Name: 國文, dtype: int32
1     82
2     86
3     69
4     59
5     84
6     63
7     87
8     66
9     60
10    93
11    56
12    93
13    51
14    52
15    90
16    88
17    93
18    82
19    92
20    85
21    73
22    51
23    83
24    91
25    59
26    85
27    65
28    72
29    85
30    59
31    91
32    89
33    80
34    72
35    80
36    71
37    58
38    85
39    90
40    94
41    74
42    50
43    68
44    53
45    61
46    99
47    90
48    96
49    68
50    92
Name: 英文, dtype: int32
1      72
2      85
3      50
4      58
5      69
6      88
7      78
8      94
9      54
10     64
11     99
12     63
13     62
14     55
15     51
16     57
17     62
18     64
19     60
20     69
21     81
22     67
23     71
24     53
25     69
26    100
27     57
28     91
29     86
30     90
31     95
32     57
33     52
34     52
35     53
36     90
37     59
38     59
39     76
40     77
41     83
42     85
43     56
44     97
45     59
46     84
47     75
48     70
49     67
50     65
Name: 數學, dtype: int32
1      91
2      98
3      81
4      52
5      94
6      56
7      65
8      69
9     100
10     66
11     93
12     96
13     68
14     91
15     71
16     66
17     58
18    100
19     79
20     98
21     98
22     59
23     86
24     66
25     83
26     96
27     78
28     77
29     81
30     73
31     66
32     84
33     90
34     59
35     71
36     67
37     95
38     94
39     82
40     91
41     66
42     65
43     72
44     71
45     92
46     53
47     56
48     88
49     87
50     84
Name: 自然, dtype: int32
1      58
2      86
3      88
4      93
5      74
6      57
7      73
8      61
9      93
10     92
11     75
12     92
13     70
14     57
15     50
16     90
17     97
18     58
19     73
20     75
21     76
22     85
23     89
24     88
25     89
26     82
27     88
28     75
29     80
30     76
31     78
32     72
33     79
34     98
35     64
36     69
37     91
38     70
39     58
40     89
41     72
42    100
43     69
44     55
45     74
46     68
47     52
48     50
49     89
50     71
Name: 社會, dtype: int32

國文    None
英文    None
數學    None
自然    None
社會    None
dtype: object

In [4]:
def abc(s):
    return s
score.apply(abc)

     國文  英文   數學   自然   社會
1    92  82   72   91   58
2    73  86   85   98   86
3    64  69   50   81   88
4   100  59   58   52   93
5    53  84   69   94   74
6    64  63   88   56   57
7    90  87   78   65   73
8    97  66   94   69   61
9    80  60   54  100   93
10   62  93   64   66   92
11   57  56   99   93   75
12   93  93   63   96   92
13   78  51   62   68   70
14   90  52   55   91   57
15   70  90   51   71   50
16   57  88   57   66   90
17   58  93   62   58   97
18   74  82   64  100   58
19   97  92   60   79   73
20   66  85   69   98   75
21   50  73   81   98   76
22   76  51   67   59   85
23   79  83   71   86   89
24   55  91   53   66   88
25   67  59   69   83   89
26   75  85  100   96   82
27   54  65   57   78   88
28   51  72   91   77   75
29   94  85   86   81   80
30   71  59   90   73   76
31   80  91   95   66   78
32   62  89   57   84   72
33   93  80   52   90   79
34   52  72   52   59   98
35   53  80   53   71   64
36   99  71   90   67   69
37   66  58   59   95   91
38   70  85   59   94   70
39   65  90   76   82   58
40   60  94   77   91   89
41   63  74   83   66   72
42   85  50   85   65  100
43   88  68   56   72   69
44   84  53   97   71   55
45   58  61   59   92   74
46   96  99   84   53   68
47   53  90   75   56   52
48   57  96   70   88   50
49   70  68   67   87   89
50   90  92   65   84   71

In [5]:
def abc(s):
    return s.max()
score.apply(abc)

國文    100
英文     99
數學    100
自然    100
社會    100
dtype: int32

In [6]:
def abc(s):
    return pd.Series([s.min(),s.max(),s.mean()],index=['最低分','最高分','平均'])
score.apply(abc)

         國文    英文     數學      自然      社會
最低分   50.00  50.0   50.0   52.00   50.00
最高分  100.00  99.0  100.0  100.00  100.00
平均    72.62  76.3   70.6   78.44   76.16

In [7]:
# 更換 index 內容
score.index = score.index.map(lambda i:f'{i}號')
score

      國文  英文   數學   自然   社會
1號    92  82   72   91   58
2號    73  86   85   98   86
3號    64  69   50   81   88
4號   100  59   58   52   93
5號    53  84   69   94   74
6號    64  63   88   56   57
7號    90  87   78   65   73
8號    97  66   94   69   61
9號    80  60   54  100   93
10號   62  93   64   66   92
11號   57  56   99   93   75
12號   93  93   63   96   92
13號   78  51   62   68   70
14號   90  52   55   91   57
15號   70  90   51   71   50
16號   57  88   57   66   90
17號   58  93   62   58   97
18號   74  82   64  100   58
19號   97  92   60   79   73
20號   66  85   69   98   75
21號   50  73   81   98   76
22號   76  51   67   59   85
23號   79  83   71   86   89
24號   55  91   53   66   88
25號   67  59   69   83   89
26號   75  85  100   96   82
27號   54  65   57   78   88
28號   51  72   91   77   75
29號   94  85   86   81   80
30號   71  59   90   73   76
31號   80  91   95   66   78
32號   62  89   57   84   72
33號   93  80   52   90   79
34號   52  72   52   59   98
35號   53  80   53   71   64
36號   99  71   90   67   69
37號   66  58   59   95   91
38號   70  85   59   94   70
39號   65  90   76   82   58
40號   60  94   77   91   89
41號   63  74   83   66   72
42號   85  50   85   65  100
43號   88  68   56   72   69
44號   84  53   97   71   55
45號   58  61   59   92   74
46號   96  99   84   53   68
47號   53  90   75   56   52
48號   57  96   70   88   50
49號   70  68   67   87   89
50號   90  92   65   84   71

In [33]:
score.iloc[2]

國文    64
英文    69
數學    50
自然    81
社會    88
Name: 3號, dtype: int32

In [8]:
def abc1(item):
    print(item)
score.apply(abc1, axis=1)   #因為axis=1

國文    92
英文    82
數學    72
自然    91
社會    58
Name: 1號, dtype: int32
國文    73
英文    86
數學    85
自然    98
社會    86
Name: 2號, dtype: int32
國文    64
英文    69
數學    50
自然    81
社會    88
Name: 3號, dtype: int32
國文    100
英文     59
數學     58
自然     52
社會     93
Name: 4號, dtype: int32
國文    53
英文    84
數學    69
自然    94
社會    74
Name: 5號, dtype: int32
國文    64
英文    63
數學    88
自然    56
社會    57
Name: 6號, dtype: int32
國文    90
英文    87
數學    78
自然    65
社會    73
Name: 7號, dtype: int32
國文    97
英文    66
數學    94
自然    69
社會    61
Name: 8號, dtype: int32
國文     80
英文     60
數學     54
自然    100
社會     93
Name: 9號, dtype: int32
國文    62
英文    93
數學    64
自然    66
社會    92
Name: 10號, dtype: int32
國文    57
英文    56
數學    99
自然    93
社會    75
Name: 11號, dtype: int32
國文    93
英文    93
數學    63
自然    96
社會    92
Name: 12號, dtype: int32
國文    78
英文    51
數學    62
自然    68
社會    70
Name: 13號, dtype: int32
國文    90
英文    52
數學    55
自然    91
社會    57
Name: 14號, dtype: int32
國文    70
英文    90
數學    51
自然    71
社會    50
Name: 15號, dtype: int32
國文    57
英文    88
數學    57
自然    66
社會    90
Name: 16號, dtype: int32
國文    58
英文    93
數學    62
自然    58
社會    97
Name: 17號, dtype: int32
國文     74
英文     82
數學     64
自然    100
社會     58
Name: 18號, dtype: int32
國文    97
英文    92
數學    60
自然    79
社會    73
Name: 19號, dtype: int32
國文    66
英文    85
數學    69
自然    98
社會    75
Name: 20號, dtype: int32
國文    50
英文    73
數學    81
自然    98
社會    76
Name: 21號, dtype: int32
國文    76
英文    51
數學    67
自然    59
社會    85
Name: 22號, dtype: int32
國文    79
英文    83
數學    71
自然    86
社會    89
Name: 23號, dtype: int32
國文    55
英文    91
數學    53
自然    66
社會    88
Name: 24號, dtype: int32
國文    67
英文    59
數學    69
自然    83
社會    89
Name: 25號, dtype: int32
國文     75
英文     85
數學    100
自然     96
社會     82
Name: 26號, dtype: int32
國文    54
英文    65
數學    57
自然    78
社會    88
Name: 27號, dtype: int32
國文    51
英文    72
數學    91
自然    77
社會    75
Name: 28號, dtype: int32
國文    94
英文    85
數學    86
自然    81
社會    80
Name: 29號, dtype: int32
國文    71
英文    59
數學    90
自然    73
社會    76
Name: 30號, dtype: int32
國文    80
英文    91
數學    95
自然    66
社會    78
Name: 31號, dtype: int32
國文    62
英文    89
數學    57
自然    84
社會    72
Name: 32號, dtype: int32
國文    93
英文    80
數學    52
自然    90
社會    79
Name: 33號, dtype: int32
國文    52
英文    72
數學    52
自然    59
社會    98
Name: 34號, dtype: int32
國文    53
英文    80
數學    53
自然    71
社會    64
Name: 35號, dtype: int32
國文    99
英文    71
數學    90
自然    67
社會    69
Name: 36號, dtype: int32
國文    66
英文    58
數學    59
自然    95
社會    91
Name: 37號, dtype: int32
國文    70
英文    85
數學    59
自然    94
社會    70
Name: 38號, dtype: int32
國文    65
英文    90
數學    76
自然    82
社會    58
Name: 39號, dtype: int32
國文    60
英文    94
數學    77
自然    91
社會    89
Name: 40號, dtype: int32
國文    63
英文    74
數學    83
自然    66
社會    72
Name: 41號, dtype: int32
國文     85
英文     50
數學     85
自然     65
社會    100
Name: 42號, dtype: int32
國文    88
英文    68
數學    56
自然    72
社會    69
Name: 43號, dtype: int32
國文    84
英文    53
數學    97
自然    71
社會    55
Name: 44號, dtype: int32
國文    58
英文    61
數學    59
自然    92
社會    74
Name: 45號, dtype: int32
國文    96
英文    99
數學    84
自然    53
社會    68
Name: 46號, dtype: int32
國文    53
英文    90
數學    75
自然    56
社會    52
Name: 47號, dtype: int32
國文    57
英文    96
數學    70
自然    88
社會    50
Name: 48號, dtype: int32
國文    70
英文    68
數學    67
自然    87
社會    89
Name: 49號, dtype: int32
國文    90
英文    92
數學    65
自然    84
社會    71
Name: 50號, dtype: int32

1號     None
2號     None
3號     None
4號     None
5號     None
6號     None
7號     None
8號     None
9號     None
10號    None
11號    None
12號    None
13號    None
14號    None
15號    None
16號    None
17號    None
18號    None
19號    None
20號    None
21號    None
22號    None
23號    None
24號    None
25號    None
26號    None
27號    None
28號    None
29號    None
30號    None
31號    None
32號    None
33號    None
34號    None
35號    None
36號    None
37號    None
38號    None
39號    None
40號    None
41號    None
42號    None
43號    None
44號    None
45號    None
46號    None
47號    None
48號    None
49號    None
50號    None
dtype: object

- " ".join()：用指定的符號來連接多個字串

In [50]:
def abc1(item):
    non_pass = item[item < 60]
    non_pass_count = non_pass.count()
    non_str = "/".join(non_pass.index.values.tolist())

    return pd.Series([item.sum(), item.mean(), non_pass_count,non_str], index=['總分','平均','不及格科目數','不及格科目'])
score.apply(abc1, axis=1)   #以橫列做為計算

      總分    平均  不及格科目數     不及格科目
1號   395  79.0       1        社會
2號   428  85.6       0
3號   352  70.4       1        數學
4號   362  72.4       3  英文/數學/自然
5號   374  74.8       1        國文
6號   328  65.6       2     自然/社會
7號   393  78.6       0
8號   387  77.4       0
9號   387  77.4       1        數學
10號  377  75.4       0
11號  380  76.0       2     國文/英文
12號  437  87.4       0
13號  329  65.8       1        英文
14號  345  69.0       3  英文/數學/社會
15號  332  66.4       2     數學/社會
16號  358  71.6       2     國文/數學
17號  368  73.6       2     國文/自然
18號  378  75.6       1        社會
19號  401  80.2       0
20號  393  78.6       0
21號  378  75.6       1        國文
22號  338  67.6       2     英文/自然
23號  408  81.6       0
24號  353  70.6       2     國文/數學
25號  367  73.4       1        英文
26號  438  87.6       0
27號  342  68.4       2     國文/數學
28號  366  73.2       1        國文
29號  426  85.2       0
30號  369  73.8       1        英文
31號  410  82.0       0
32號  364  72.8       1        數學
33號  394  78.8       1        數學
34號  333  66.6       3  國文/數學/自然
35號  321  64.2       2     國文/數學
36號  396  79.2       0
37號  369  73.8       2     英文/數學
38號  378  75.6       1        數學
39號  371  74.2       1        社會
40號  411  82.2       0
41號  358  71.6       0
42號  385  77.0       1        英文
43號  353  70.6       1        數學
44號  360  72.0       2     英文/社會
45號  344  68.8       2     國文/數學
46號  400  80.0       1        自然
47號  326  65.2       3  國文/自然/社會
48號  361  72.2       2     國文/社會
49號  381  76.2       0
50號  402  80.4       0

In [14]:
count['班排名'] = count['總分'].rank(ascending=False)
count

        總分    平均   班排名
1號   395.0  79.0  12.0
2號   428.0  85.6   3.0
3號   352.0  70.4  40.0
4號   362.0  72.4  33.0
5號   374.0  74.8  25.0
6號   328.0  65.6  48.0
7號   393.0  78.6  14.5
8號   387.0  77.4  16.5
9號   387.0  77.4  16.5
10號  377.0  75.4  24.0
11號  380.0  76.0  20.0
12號  437.0  87.4   2.0
13號  329.0  65.8  47.0
14號  345.0  69.0  41.0
15號  332.0  66.4  46.0
16號  358.0  71.6  36.5
17號  368.0  73.6  29.0
18號  378.0  75.6  22.0
19號  401.0  80.2   9.0
20號  393.0  78.6  14.5
21號  378.0  75.6  22.0
22號  338.0  67.6  44.0
23號  408.0  81.6   7.0
24號  353.0  70.6  38.5
25號  367.0  73.4  30.0
26號  438.0  87.6   1.0
27號  342.0  68.4  43.0
28號  366.0  73.2  31.0
29號  426.0  85.2   4.0
30號  369.0  73.8  27.5
31號  410.0  82.0   6.0
32號  364.0  72.8  32.0
33號  394.0  78.8  13.0
34號  333.0  66.6  45.0
35號  321.0  64.2  50.0
36號  396.0  79.2  11.0
37號  369.0  73.8  27.5
38號  378.0  75.6  22.0
39號  371.0  74.2  26.0
40號  411.0  82.2   5.0
41號  358.0  71.6  36.5
42號  385.0  77.0  18.0
43號  353.0  70.6  38.5
44號  360.0  72.0  35.0
45號  344.0  68.8  42.0
46號  400.0  80.0  10.0
47號  326.0  65.2  49.0
48號  361.0  72.2  34.0
49號  381.0  76.2  19.0
50號  402.0  80.4   8.0

In [43]:
one_student = score.iloc[0]  #調出 index=0 的學生分數
print(one_student)
non_pass = one_student[one_student < 60]  #從分數中調出符合條件的數據
non_pass

國文    92
英文    82
數學    72
自然    91
社會    58
Name: 1號, dtype: int32

社會    58
Name: 1號, dtype: int32

In [44]:
print(non_pass.count())    #數據數量
print(non_pass.index)      #查詢滿足作為引數傳遞的布林條件的 DataFrame 的匹配索引
print(non_pass.index.values)    # value 返回给定DataFrame的numpy表示形式
",".join(non_pass.index.values.tolist())   ## tolist(實體方法) 把 tolist() 放在 index() 方法後面，是為了把 Index 轉換為列表list

1
Index(['社會'], dtype='object')
['社會']

'社會'